---
- hosts: websever
  tasks:
    - name: change permission
      shell: sudo chmod 777 /var/run/docker.sock
    
    - name: login to jfrog
      shell: docker login -u chandanabn95@gmail.com -p Password@1 hostname1.jfrog.io
    
    - name: pull an image
      shell: docker pull hostname1.jfrog.io/docker-test/devops_practice:{{ BUILD_NUMBER }}

    #- name: remove container
    #   shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 hostname1.jfrog.io/docker-test/devops_practice:{{ BUILD_NUMBER }}
