---
- hosts: websever
  become: yes
  #become_user: tomcat
  vars:
   build_number: '{{BUILD_NUMBER}}' 
  tasks:

  - name: create directory 
    file:
      path: /home/tomcat/sourcefile
      state: directory
      mode: 0777

  - name: download war file
    ansible.builtin.get_url:
      url: https://hostname1.jfrog.io/artifactory/jfrog-test/webapp-{{BUILD_NUMBER}}.war
      #url: https://hostname1.jfrog.io/artifactory/jfrog-test/*.war
      dest: /home/tomcat/sourcefile/webapp.war
      username: chandanabn95@gmail.com
      password: Password@1

  - name: create directory with a date in name
    file: 
      path: /home/tomcat/backup
      state: directory
      mode: 0777

  - name: backup file with owner and permissions
    copy:
      src: /opt/tomcat/webapps/webapp.war
      dest: /home/tomcat/backup/webapp.war
      remote_src: yes

  - name: Delete remote war file
    file:
      path: /opt/tomcat/webapps/webapp.war
      state: absent

  - name: deploy file with owner and permissions
    #become: yes
    #become_user: root
    copy:
      src: /home/tomcat/sourcefile/webapp.war
      dest: /opt/tomcat/webapps/webapp.war
      remote_src: yes
